[workspace]
resolver = "3"
members = [
    "crates/ah-abi",
    "crates/ah-core",
    "crates/ah-plugin-sdk",
    "crates/ah-remote-proto",
    "crates/ah-voice",
    "crates/ah",
]
exclude = ["plugins"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 0
