[package]
name = "ah-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ah-abi = { path = "../ah-abi" }
serde = { workspace = true, features = ["std"] }
serde_json = { workspace = true, features = ["std"] }
ureq = { version = "3", default-features = false, features = ["rustls", "json", "gzip"] }
toml = { version = "0.9", default-features = false, features = ["parse", "display", "serde"] }
wasmi = "2"
zeroize = "1"
dirs = "7"
